version: '3'
services:
  ts:
    container_name: ts
    build: ./
    image: ts:latest
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
      - 5858:5858
    command: ['node', '--debug=0.0.0.0:5858', '/var/www/dist/Server.js']
